version: '3'
networks:
  frontend:
    name: im-front
    driver: bridge
  backend:
    name: im-back
    driver: bridge

volumes:
  wslog:
    name: wslog
    driver: local
  roomlog:
    name: roomlog
    driver: local
  httplog:
    name: httplog
    driver: local

services:
  room:
    image: im-room:v1.0
    container_name: im-room
    build: ./manage
    restart: always
    networks:
      - backend
    volumes:
      - roomlog:/usr/src/app/logs
  http:
    image: im-http:v1.0
    container_name: im-http
    build: ./httpsrv
    networks:
      - backend
      - frontend
    links:
      - room
    restart: always
    ports:
    - "80:80"
    volumes:
      - httplog:/usr/src/app/logs
  ws:
    image: im-ws:v1.0
    container_name: im-ws
    build: ./ws
    networks:
      - backend
      - frontend
    restart: always
    links:
      - room
    ports:
    - "5555:5555"
    volumes:
    - wslog:/usr/src/app/logs

