# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import room_pb2 as room__pb2


class RoomStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/Room/Create',
                request_serializer=room__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=room__pb2.CreateRoomResponse.FromString,
                )
        self.Validate = channel.unary_unary(
                '/Room/Validate',
                request_serializer=room__pb2.ValidateRoomRequest.SerializeToString,
                response_deserializer=room__pb2.ValidateRoomResponse.FromString,
                )
        self.Join = channel.unary_unary(
                '/Room/Join',
                request_serializer=room__pb2.JoinRoomRequest.SerializeToString,
                response_deserializer=room__pb2.JoinRoomResponse.FromString,
                )
        self.GetRoomAddr = channel.unary_unary(
                '/Room/GetRoomAddr',
                request_serializer=room__pb2.GetRoomAddrRequest.SerializeToString,
                response_deserializer=room__pb2.GetRoomAddrResponse.FromString,
                )
        self.Leave = channel.unary_unary(
                '/Room/Leave',
                request_serializer=room__pb2.LeaveRoomRequest.SerializeToString,
                response_deserializer=room__pb2.LeaveRoomResponse.FromString,
                )
        self.GetRoomNumByAddr = channel.unary_unary(
                '/Room/GetRoomNumByAddr',
                request_serializer=room__pb2.GetRoomNumByAddrRequest.SerializeToString,
                response_deserializer=room__pb2.GetRoomNumByAddrResponse.FromString,
                )


class RoomServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoomAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoomNumByAddr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=room__pb2.CreateRoomRequest.FromString,
                    response_serializer=room__pb2.CreateRoomResponse.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=room__pb2.ValidateRoomRequest.FromString,
                    response_serializer=room__pb2.ValidateRoomResponse.SerializeToString,
            ),
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=room__pb2.JoinRoomRequest.FromString,
                    response_serializer=room__pb2.JoinRoomResponse.SerializeToString,
            ),
            'GetRoomAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomAddr,
                    request_deserializer=room__pb2.GetRoomAddrRequest.FromString,
                    response_serializer=room__pb2.GetRoomAddrResponse.SerializeToString,
            ),
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=room__pb2.LeaveRoomRequest.FromString,
                    response_serializer=room__pb2.LeaveRoomResponse.SerializeToString,
            ),
            'GetRoomNumByAddr': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomNumByAddr,
                    request_deserializer=room__pb2.GetRoomNumByAddrRequest.FromString,
                    response_serializer=room__pb2.GetRoomNumByAddrResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Room', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Room(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Room/Create',
            room__pb2.CreateRoomRequest.SerializeToString,
            room__pb2.CreateRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Room/Validate',
            room__pb2.ValidateRoomRequest.SerializeToString,
            room__pb2.ValidateRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Room/Join',
            room__pb2.JoinRoomRequest.SerializeToString,
            room__pb2.JoinRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoomAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Room/GetRoomAddr',
            room__pb2.GetRoomAddrRequest.SerializeToString,
            room__pb2.GetRoomAddrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Room/Leave',
            room__pb2.LeaveRoomRequest.SerializeToString,
            room__pb2.LeaveRoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoomNumByAddr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Room/GetRoomNumByAddr',
            room__pb2.GetRoomNumByAddrRequest.SerializeToString,
            room__pb2.GetRoomNumByAddrResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
